name: 'Hello World'
description: 'Greet someone'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'Cool Duck!'
outputs:
  duck_output:
    description: "Random number"
    value: ${{ steps.get-ducks.outputs.duck }}
runs:
  using: "composite"
  steps:
    - uses: action/checkout@2
    
    - run: echo Hello ${{ inputs.who-to-greet }}.
      shell: bash
    
    - id: get-ducks
      run: echo "::set-output name=duck::$(echo $RANDOM)"
      shell: bash

    - id: get-ducks
      run: echo "::set-output name=duck::$(awk '{print $1' ducks.txt | paste -s -d, -)"
      shell: bash
