name: 'Hello World'
description: 'Greet someone'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'Cool Duck!'
outputs:
  duck_output:
    description: "Random number"
    value: ${{ steps.get-ducks.outputs.duck }}
runs:
  using: "composite"
  steps:
    - uses: action/checkout@v2
      with:
       ref: main
       repository: TeddyBrod/Composite-action
       token: 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
    
    - run: echo Hello ${{ inputs.who-to-greet }}.
      shell: bash

    - id: get-ducks
      run: echo "::set-output name=duck::$(awk '{print $1' ducks.txt | paste -s -d, -)"
      shell: bash
